pipeline {
    agent any

    environment { 
        REGION = "ap-northeast-2"
        ECR_REPOSITORY = "182024812696.dkr.ecr.${ENV.REGION}.amazonaws.com"
        CONTINAER_NAME = "todolist-repository:build"
        CREDENTIALS="leedonggyu-aws-credentials"
    }    

    // 원래는 다 환경변수에 담아서 .. 진행하자..

    stages {
        stage('Push ECR') {
            steps {
                dir("apiserver") {
                    script {
                        def searchString = "&&BUILD_ID&&"
                        def pipelineScriptPath = "deploy/task-definition.json"
                        
                        // Read to Json file
                        def pipelineScriptContent = readFile(file: pipelineScriptPath)

                        // Replace the string
                        def updatedPipelineScript = pipelineScriptContent.replace(searchString, env.BUILD_ID)
                        writeFile(file: pipelineScriptPath, text: updatedPipelineScript)

                        sh "docker build -t build-${env.BUILD_ID} ."
                        sh "docker tag build-${env.BUILD_ID} ${env.ECR_REPOSITORY}/${env.CONTINAER_NAME}-${env.BUILD_ID}"

                        docker.withRegistry("https://${env.ECR_REPOSITORY}/${env.CONTINAER_NAME}-${env.BUILD_ID}", "ecr:${env.REGION}:${env.CREDENTIALS}") {
                            docker.image("${env.ECR_REPOSITORY}/${env.CONTINAER_NAME}-${env.BUILD_ID}").push()
                        }
                    }
                }
            }
        }

        // stage("Deploy ECS via CodeDeploy") {
            steps {
                dir("apiserver/deploy") {
                    script {
                        withAWS(credentials: "${env.CREDENTIALS}", region: "${env.REGION}") {
                            sh "aws deploy create-deployment --application-name todolist-ecs-app --deployment-group-name todolist-ecs-deployment-group --revision revisionType=AppSpecContent,value=\"$(cat appspec.yml)\""
                        }
                    }
                }
            }
        }
}
