pipeline {
    agent any

    stages {
        stage('Push ECR') {
            steps {
                dir("apiserver") {
                    script {
                        sh "docker build -t build-latest ."
                    }
                }
            }
        }

        stage("Deploy ECS") {
            steps {
                dir("apiserver/deploy") {
                    sh "ls"
                }
            }
        }
    }
}
