pipeline {
    agent any

    stages {
        stage('Push ECR') {
            steps {
                dir("apiserver") {
                    script {
                        sh "docker build -t build-latest ."
                        sh "docker tag build-latest 182024812696.dkr.ecr.ap-northeast-2.amazonaws.com/todolist-repository:build-latest"

                        docker.withRegistry("https://182024812696.dkr.ecr.ap-northeast-2.amazonaws.com/todolist-repository:build-latest", "ecr:ap-northeast-2:leedonggyu-aws-credentials") {
                            docker.image("182024812696.dkr.ecr.ap-northeast-2.amazonaws.com/todolist-repository:build-latest").push()
                        }

                    }
                }
            }
        }

        stage("Deploy ECS") {
            steps {
                dir("apiserver/deploy") {
                    sh "ls"
                }
            }
        }
    }
}
