pipeline {
    agent any

    stages {
        stage('Deploy ECS') {
            steps {
                script {
                    dir("apiserver"){
                        sh "docker build -t 182024812696.dkr.ecr.ap-northeast-2.amazonaws.com/todolist-repository:build-latest ."
                    }
                }
            }
        }
    }
}
