pipeline {
    agent any

    stages {
        stage('Push ECR') {
            steps {
                script {
                    dir("apiserver"){
                        sh "ls"
                        // sh "docker build -t 182024812696.dkr.ecr.ap-northeast-2.amazonaws.com/todolist-repository:build-latest ."
                    }
                }
            }
        }

        stage("")
    }
}
